=== sy527991/Citation-Network/teidtd.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT TEI (teiHeader,text)>
<!ATTLIST TEI
  xml:id CDATA #IMPLIED >


<!-- ===============================================  -->
<!--    teiHeader element                             -->
<!-- ===============================================  -->

<!ELEMENT teiHeader (fileDesc)>
<!ELEMENT fileDesc (titleStmt,publicationStmt, sourceDesc)>

<!ELEMENT titleStmt (title+,author)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  type (main | sub) #REQUIRED
  xml:id CDATA #IMPLIED
  n CDATA #IMPLIED
  ko CDATA #REQUIRED>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author
  birth CDATA #REQUIRED
  death CDATA #REQUIRED
  ko CDATA #REQUIRED>

<!ELEMENT publicationStmt (title,resp,name,idno)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  ko CDATA #FIXED>
<!ELEMENT resp (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  ko CDATA #REQUIRED>
<!ELEMENT idno (#PCDATA)>
<!ATTLIST idno
  type CDATA #REQUIRED>

<!ELEMENT sourceDesc (bibl)>
<!ELEMENT bibl (title,publisher,pubPlace,date)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  ko CDATA #REQUIRED>
<!ELEMENT publisher (#PCDATA)>
<!ATTLIST publisher
  ko CDATA #REQUIRED>
<!ELEMENT pubPlace (#PCDATA)>
<!ATTLIST pubPlace
  ko CDATA #REQUIRED>
<!ELEMENT date (#PCDATA)>


<!-- ===============================================  -->
<!--    text element                                  -->
<!-- ===============================================  -->

<!ELEMENT text (front?,body,back?)>
<!ATTLIST text
  xml:id CDATA #IMPLIED
  xml:lang CDATA #IMPLIED>
  
<!ELEMENT front (list,head,div)+>
<!ELEMENT list (item,label?)+>
<!ELEMENT item (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT head (#PCDATA)>
<!ATTLIST head
  type CDATA #IMPLIED
  ko CDATA #REQUIRED>
<!ELEMENT div (#PCDATA)>
<!ATTLIST div
  type CDATA #IMPLIED>

<!ELEMENT back (note)+>
<!ELEMENT note (#PCDATA)>
<!ATTLIST note
  place CDATA #IMPLIED
  type CDATA #IMPLIED
  ko CDATA #REQUIRED>

<!ELEMENT body (head,group+)>
<!ELEMENT head (#PCDATA)>
<!ATTLIST head
  type CDATA #REQUIRED
  n CDATA #IMPLIED
  ko CDATA #REQUIRED>
<!ELEMENT group (div)+>
<!ATTLIST group
  xml:id CDATA #REQUIRED
  type CDATA #REQUIRED
  n CDATA #IMPLIED>
<!ELEMENT div (#PCDATA|quoted)*>
<!ATTLIST div
  n CDATA #IMPLIED
  type (經文 | 中國註釋 | 原註 | 細註 ) #REQUIRED>

<!ELEMENT quoted (#PCDATA)>
<!ATTLIST quoted
  who CDATA #IMPLIED
  what CDATA #IMPLIED
  which CDATA #IMPLIED
  how CDATA #IMPLIED
  pattern CDATA #IMPLIED
  purpose CDATA #IMPLIED
  similar CDATA #IMPLIED>

=== sy527991/Citation-Network/tei사변록.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI SYSTEM "https://dh.aks.ac.kr/~kimseoyun/101/reserch_note/xml/teidtd.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
 
  <teiHeader xml:id="018_13">
    <fileDesc>
      <titleStmt>
        <title type="main" ko="사변록">思辨錄</title>
        <title type="sub" xml:id="C" n="1" ko="논어">論語</title>
        <author pid="ko1629" birth="1629" death="1703" ko="박세당">朴世堂</author>
      </titleStmt>

      <publicationStmt>
        <title ko="한국경학자료시스템">Complete Collection of the Korean Study of Confucian Classics</title>
        <resp>copyright(c) 2004 All rights reserved</resp>    
        <name ko="성균관대학교존경각">成均館大學校尊經閣</name>
        <idno type="URI">http://koco.skku.edu/main.jsp</idno>
      </publicationStmt>

      <sourceDesc> 
        <bibl>
        <title ko="한국경학자료집성">韓國經學資料集成</title>
        <publisher ko="성균관대학교대동문화연구원">成均館大學校大東文化硏究院</publisher>
        <pubPlace ko="성균관대학교출판부">成均館大學校出版部</pubPlace>
        <date>1990-02-20</date>
        </bibl>
      </sourceDesc>

    </fileDesc>
  </teiHeader>
    
  <text xml:id="JCXL018_13_0001" xml:lang="zh">
    <front>       
      <head type="main" ko="사변록">思辨錄</head>
      <head type="sub" ko="논어">論語</head>
    </front>

    <body>
      <head type="chapter" n="001" ko="학이제일">學而第一</head>
      <group xml:id="30001" type="section" n="g1">
        <div type="細註" n="002">凡十六章</div>
        <div type="經文" n="003">子曰學而時習之不亦說乎</div>
        <div type="原註" n="004">人従師讀書質問講究求知行己䖏物之方是謂之學既得其方又須熟習理明㓛到其心說喜若荒嬉者安得有此乎
            ○<quoted who="朱子" what="論語集注" which="中引" how="明引" similar="摘引" pattern="分引" purpose="補引">
            學雖可訓為效</quoted>但只言效則恐於傳受講質之義或有未備
            <quoted who="謝良佐" what="論語集注" which="中引" how="明引" similar="摘引" pattern="分引" purpose="補引">
            上蔡之說雖巧殊非孔子本㫖坐如尸立如齊</quoted>此只荘敬自修不可取作學習之一事
            <quoted who="朱子" what="朱子語類" which="中引" how="明引" similar="改引" purpose="疑引">
            朱子謂伊川之說専在思索上蔡之說専扵力行似皆偏了</quoted>
            今觀伊川後說固不専思索而若如上蔡其失恐不但在偏而已盖論釋經義只當深明立言本意不當泛濫㫄出如此也</div>
        <div type="經文" n="005">有朋自遠方来不亦楽乎</div>
        <div type="原註" n="006">君子恥獨善其身則朋来之楽可知也</div>
        <div type="經文" n="007">人不知而不愠不亦君子乎</div>
        <div type="原註" n="008">
            <quoted who="程子" what="論語集注" which="中引" how="明引" similar="全引" pattern="連引" purpose="駁引">
            程子謂楽由說而後得非楽不足以語君子</quoted>
            <quoted who="朱熹" what="朱子語類" which="中引" how="明引" similar="全引" pattern="連引" purpose="駁引">
            朱子亦曰惟楽後方䏻進步不楽則何道以為君子</quoted>及
            <quoted who="朱熹" what="論語集注" which="中引" how="明引" similar="全引" pattern="連引" purpose="駁引">
            其所云徳之所以成亦由學之正習之熟說之深而不已焉</quoted>亦夲此說盖皆推極之言然皆在夫子所言之外恐妨讀者反生疑晦耳</div>
      </group>

      <group xml:id="30003" type="section" n="g2">
        <div type="經文" n="001">○子曰巧言令色鮮矣仁</div>
        <div type="原註" n="002">忠信所以為仁巧言令色遠於忠信</div>
      </group>

      <group xml:id="30005" type="section" n="g3">
        <div type="經文" n="001">○子曰道千乗之國敬事而信節用而愛人使民以時</div>
        <div type="原註" n="002">徒知節用而不䏻愛人其敝為吝既䏻節用又䏻愛人推其所節可以有濟所以為貴
            <quoted who="朱熹" what="論語集注" which="中引" how="明引" similar="改引" pattern="連引" purpose="補引">
            ○敬訓以主一無適</quoted>此但敬之一事恐未盡其義敬只是謹戰戰兢兢臨深履薄即此為敬戰兢則自無他適若但主一而無戰兢之意豈得為敬
            <quoted who="楊時" what="論語集注" which="中引" how="明引" similar="改引" pattern="連引" purpose="補引">
            ○龜山謂此特論其所存而已未及為政</quoted>其說甚疎夫敬事節用使民非政而何政有外於此三者乎
            <quoted who="胡宏" what="論語集注" which="中引" how="明引" similar="全引" pattern="連引" purpose="駁引">
            胡氏又謂凡此數者又皆以敬為主</quoted>
            朱子又推釋其義竊謂敬固無事而可闕然學者於聖人之言必先求所以言之㫖虗心遜志以深軆之然後方有所得以敬為主
            恐非此章之夲㫖不如各致其義所得為深也若先自立標凖盡驅經義納於其中恐未可也</div>
      </group>

      <group xml:id="30006" type="section" n="g4">
        <div type="經文" n="001">○子曰弟子入則孝出則弟謹而信汎愛衆而親仁行有餘力則以學文</div>
        <div type="原註" n="002">事無不謹必䏻信之為貴人無不愛必親仁之是急</div>
      </group>
      
      <group xml:id="30008" type="section" n="g5">
        <div type="經文" n="001">○子曰君子不重則不威學則不固主忠信無友不如己者過則勿憚攺</div>
        <div type="原註" n="002">不重則外不䏻畏服乎人内不䏻堅固其所守此君子所以貴重</div>
      </group>
        
      <group xml:id="30010" type="section" n="g6">        
        <div type="經文" n="001">○子禽問於子貢曰夫子至於是邦也
            必聞其政求之與抑與之與子貢曰夫子温良恭儉讓以得之夫子之求之也其諸異乎人之求之與</div>
        <div type="原註" n="002">
            <quoted who="朱熹" what="論語集注" which="中引" how="明引" similar="全引" pattern="連引" purpose="補引">
            朱子謂徳容如是故時君敬信</quoted>
            <quoted who="謝良佐" what="論語集注" which="中引" how="明引" similar="改引" pattern="分引" purpose="補引">
            謝氏謂觀於聖人威儀之間亦可以進徳</quoted>
            <quoted who="張栻" what="論語集注" which="中引" how="明引" similar="改引" pattern="分引" purpose="補引">
            南軒謂盖見聖人之儀刑而楽告之</quoted>
            據此三說温良恭儉讓似只為容儀之著乎外者然子貢之意但謂聖人有此五徳之實故人自信服耳上三說亦謂聖人徳充于内而符見于外者如此
            非直謂温良恭儉讓但是外面事然其說未備</div>
      </group>

      <group xml:id="30013" type="section" n="g7">
        <div type="經文" n="001">○有子曰信近於義言可復也恭近扵禮遠耻辱也因不失其親亦可宗也</div>
        <div type="原註" n="002">非義之信踐行也難非禮之恭恥辱斯甚
            <quoted who="司馬遷" what="史記" which="經引" how="藏引" similar="摘引" pattern="分引" purpose="借引">
            因猶因景監之因</quoted>苟所因不擇可親之人則雖其由此得志其成效粗有可稱其夲汚賤人所卑下必其所因者得其可親然後正己好徳之實為可宗也
            <quoted who="朱熹" what="論語集注" which="中引" how="明引" similar="摘引" pattern="分引" purpose="駁引">
            ○朱子謂因勢敵宗彼尊</quoted>
            <quoted who="朱熹" what="論語集注" which="中引" how="明引" similar="摘引" pattern="分引" purpose="駁引">
            又謂須於其初審其可親者従而主之</quoted>恐未然也</div>
      </group>

      <group xml:id="30014" type="section" n="g8">
        <div type="經文" n="001">○子曰君子食無求飽居無求安敏於事而慎於言就有道而正焉可謂好學也已</div>
        <div type="原註" n="002">不求安飽志之篤敏事慎言行之力此非好學者不䏻猶必就正有道然後眞可謂之好學不然非
            但言行得失無以自考而易流於頗僻是其安於小成不求進益雖欲謂之好學不可得也</div>
      </group>

      <group xml:id="30016" type="section" n="g9">
        <div type="經文" n="001">○子曰不患人之不己知患不知人也</div>
        <div type="原註" n="002">不己知與不知人此内外之辨也學者但當務内不當務外○人不知己病在人己不知人病在己故不憂彼而憂此也</div>
      </group>
    </body>
  </text>  
</TEI>
